name: DevSecOps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3
      - name: Jalankan Tes
        run: |
          echo "Testing script..."
          bash latihan-cicd/test.sh

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3
      - name: Build Project
        run: |
          chmod +x latihan-cicd/build.sh
          ./latihan-cicd/build.sh
